datasources:
  default:
    url: jdbc:postgresql://citus_master:5432/${CITUS_DB}
    username: ${CITUS_USER}
    password: ${CITUS_PASSWORD}
    driverClassName: org.postgresql.Driver
    connection-init-sql: "SET statement_timeout = '5s'"

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration